### PR TITLE
chore: introduce `black` formatting

### PR DESCRIPTION
**Pull request by tombh**
Black is an opinionated code formatter https://black.readthedocs.io/en/stable/

This introduces a _lot_ of formatting changes.

~This has the downside of now assigning all these changes to me, the committer, which means we lose some nuance as to the history and context of the original changes. But maybe it is better to "rip the bandage" to begin enjoying consistent formatting?~ This isn't actually such a problem because of `.git-blame-ignore-revs`

TODO:
* [x] Even though Black is designed to be minimally configurable, there are some options, such as setting the max line length (defaut is 88): https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html
* [x] `scripts/generate_client.py` currently outputs non Black-compatible code. We could either make it output compatible code, or just add a compulsory Black formatting step. I think we just add the extra Black format step.

## Code review checklist (for code reviewer to complete)

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated, as appropriate
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly

[commit messages]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by alcarney** [comment]
> This has the downside of now assigning all these changes to me, the committer, which means we lose some nuance as to the history and context of the original changes.

I stumbled across something that might help with this a little while ago - [.git-blame-ignore-revs](https://github.com/NixOS/nixpkgs/blob/master/.git-blame-ignore-revs) it looks like you can configure git to ignore some commits when doing a `git blame`

Looks like GitHub [supports it](https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/) too

**Comment by tombh** [comment]
Nice! Added it 😀

**Comment by dimbleby** [comment]
> `scripts/generate_client.py` currently outputs non Black-compatible code

another way would be just not to format the generated code
```
[tool.black]
exclude = "pygls/lsp/whatever"
```

**Comment by tombh** [comment]
Nice idea! Updated and all green CI now, thanks.

**Review by alcarney — APPROVED** [review]

**Pull request merged**
