### PR TITLE
Add `await` syntax support for sending edit request to client

### PR DESCRIPTION
**Pull request by oliversen**
## Description (e.g. "Related to ...", etc.)

Before:
```python
def edit_callback(future):
    result = future.result()
ls.apply_edit(workspace_edit).add_done_callback(edit_callback)
```

After:
```python
result = await ls.apply_edit_async(workspace_edit)
```

## Code review checklist (for code reviewer to complete)

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated, as appropriate
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly
- [ ] [CONTRIBUTORS.md][contributors] was updated, as appropriate
- [ ] Changelog has been updated, as needed (see [CHANGELOG.md][changelog])

[changelog]: https://github.com/openlawlibrary/pygls/blob/master/CHANGELOG.md
[commit messages]: https://chris.beams.io/posts/git-commit/
[contributors]: https://github.com/openlawlibrary/pygls/blob/master/CONTRIBUTORS.md

### CODE REVIEW

**Comment by tombh** [comment]
Thanks for the PR. Is this just a quality of life thing? As in await/async is just more conventional? Or is there a deeper more practical reason?

I wonder if this could be applied as default to all calls that use `send_request`?

**Comment by perrinjerome** [comment]
This seems to make sense, there's similar pattern with 
https://github.com/openlawlibrary/pygls/blob/464846b1205db087b66624b0e08357ef2703dfd7/pygls/progress.py#L36
and
https://github.com/openlawlibrary/pygls/blob/464846b1205db087b66624b0e08357ef2703dfd7/pygls/progress.py#L52

I'm wondering, why not define `apply_edit_async` with `async def` ?

**Comment by oliversen** [comment]
> Is this just a quality of life thing? As in await/async is just more conventional? Or is there a deeper more practical reason?

The code is cleaner, simpler, clearer (see issue description).

On the practical side we can form a response for the client, depending on the result of editing the workspace.

```python
from pygls import server

LSP_SERVER = server.LanguageServer(...)

@LSP_SERVER.command('some_command')
async def some_command(ls: server.LanguageServer):
    ...
    result = await ls.apply_edit_async(WorkspaceEdit(...))
    if result.applied:
        response = ResponseMessage(...)
    else:
        response = ResponseMessage(...)
    return response
```

> I'm wondering, why not define `apply_edit_async` with `async def` ? 

No, `async def` is not needed in this case.

https://github.com/openlawlibrary/pygls/blob/main/pygls/server.py#L390C1-L391C84
https://github.com/openlawlibrary/pygls/blob/main/pygls/server.py#L395C1-L395C95
https://github.com/openlawlibrary/pygls/blob/main/pygls/server.py#L452C1-L453C86
https://github.com/openlawlibrary/pygls/blob/main/pygls/server.py#L457C1-L457C81

> I wonder if this could be applied as default to all calls that use send_request?

How to understand "applied by default"? *Features* and *commands* can be registered as synchronous and asynchronous functions. All methods that use `send_request()` already have an asynchronous counterpart, except `apply_edit()`.

**Comment by tombh** [comment]
Ohh, so you're just filling in a missing part of a convention we already have. That makes total sense. Ok, LGTM 🚢

Regarding the `async def` syntax, that would certainly make more sense to me, but then I'm not that familiar with the  `asyncio.Future` pattern. And besides, this PR is simply about completing a pattern that we are already using elsewhere. Maybe we can convert to the `async def` pattern another time.

It looks like you just need to rebase `main` and I we can get this merged. Thank you ✨

**Comment by RossBencina** [comment]
>It looks like you just need to rebase main and I we can get this merged. Thank you ✨

bump @oliversen 

can I help?

**Comment by oliversen** [comment]
> bump @oliversen

Done!

**Comment by tombh** [comment]
The CI lint error wants a commit message more like `feat: add await syntax support for sending edit request to client`.

And a rebase from main to get the latest changes.

**Comment by tombh** [comment]
Sorry I didn't notice before, but the commit also needs formatting with [`black`](https://github.com/psf/black).

**Comment by oliversen** [comment]
> Sorry I didn't notice before, but the commit also needs formatting with [`black`](https://github.com/psf/black).

Very strange, I have no problems with formatting.
black

**Comment by tombh** [comment]
I love your prompt 🥹

This is the diff I'm seeing `black` ask for:
```diff
diff --git a/pygls/protocol.py b/pygls/protocol.py
index 62b1f8a..28b7d90 100644
--- a/pygls/protocol.py
+++ b/pygls/protocol.py
@@ -746,8 +746,9 @@ class LanguageServerProtocol(JsonRPCProtocol, metaclass=LSPMeta):
         self, edit: WorkspaceEdit, label: Optional[str] = None
     ) -> WorkspaceApplyEditResponse:
         """Sends apply edit request to the client. Should be called with `await`"""
-        return self.send_request_async(WORKSPACE_APPLY_EDIT,
-                                       ApplyWorkspaceEditParams(edit=edit, label=label))
+        return self.send_request_async(
+            WORKSPACE_APPLY_EDIT, ApplyWorkspaceEditParams(edit=edit, label=label)
+        )

     @lsp_method(EXIT)
     def lsp_exit(self, *args) -> None:

```

I see your prompt is saying it's on branch `main`, maybe you need to checkout the `add-await-syntax-support` branch?

**Review by tombh — APPROVED** [review]

**Pull request merged**
