### PR TITLE
Run tests and linters on multiple python versions and on linux

### LINKED ISSUE #96: Run test suite on multiple python versions and also on linux
https://github.com/openlawlibrary/pygls/blob/master/appveyor.yml only runs tests for python3.5 on windows.

It would be nice to run tests on other python versions, isn't it ?

I started a patch that would run tests on a matrix like this: https://ci.appveyor.com/project/perrinjerome/pygls/builds/29961016 . Patch is still very dirty, there's lots of duplication ( it's https://github.com/perrinjerome/pygls/commit/8879078854e2c2ccf22b5c6b380032c0e8a8a2d9 ), but what are your thoughts on this ?  And about using tox ? (tox makes it easier for developers to run test suite on multiple python versions as long as they have these versions installed locally)

### PR DESCRIPTION
**Pull request by perrinjerome**
## Description (e.g. "Related to ...", etc.)

 - Run typechecker (mypy) as part of test suite
 - Run on multiple python versions
 - Run on linux

Fixes #96 

## Code review checklist (for code reviewer to complete)

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated, as appropriate
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly
- [ ] [CONTRIBUTORS.md][contributors] was updated, as appropriate
- [ ] Changelog has been updated, as needed (see [CHANGELOG.md][changelog])

[changelog]: https://github.com/openlawlibrary/pygls/blob/master/CHANGELOG.md
[commit messages]: https://chris.beams.io/posts/git-commit/
[contributors]: https://github.com/openlawlibrary/pygls/blob/master/CONTRIBUTORS.md

### CODE REVIEW

**Comment by perrinjerome** [comment]
This is work in progress, this also contain the changes from #99 so that mypy test also pass.

This has 8 jobs:  4 python versions * 2 OS versions, maybe we don't need so much and testing for example all python versions on windows and only python 3.8 on linux is enough.

**Comment by perrinjerome** [comment]
This uses a trick from https://andrewlock.net/building-asp-net-core-apps-on-both-windows-and-linux-using-appveyor/#2-update-your-build-script-optional- to run windows only commands with `ps: >`.

There was some power shell steps to check the example extension, I have not adapted this for linux, this part is only tested on windows.

**Comment by bollwyvl** [comment]
I'd _highly_ recommend getting off appveyor in favor of azure pipelines (10 concurrent machines) or github actions (20 concurrent machines).

**Comment by danixeee** [comment]
I forgot that we already have one [project](https://dev.azure.com/openlawlibrary/TAF/_build) in Azure under our organisation, so we could switch this one as well. @dgreisen Thoughts?

**Comment by perrinjerome** [comment]
I have updated this, for now to include profiles to run tests on both appveyor and azure-pipelines, but the idea is that we should decide and keep only one.

I have configured my fork of pygls to run on azure and on azure, it looks like this 
https://github.com/perrinjerome/pygls/runs/422242124 and for appveyor we can see this on this PR, it's https://ci.appveyor.com/project/oll-team/pygls/builds/30524438 .

Total time on azure was 4m 12s. Total time on appveyor was 5m 49s ... which is strange because it's not the sum of all tests runs. This is the timing reported by both platforms.

Test pass on all python versions for both platforms, but:
 - I had to add a `MANIFEST.in` for python3.5 compatibility. For more details, python 3.5.9 ( the version appveyor has for ubuntu) was OK, but the problem happened on python 3.5.4 (the version appveyor has for windows) was not. I no longer have traceback, but it was something like README.md not found during install. I have not investigated this further.
 - appveyor pipeline builds a .vsix of the sample json extension ( https://ci.appveyor.com/project/oll-team/pygls/builds/30402659/artifacts ) on appveyor this is only for windows. The steps to build the extension are written in powershell and it did not seem easy to make this work on linux so I did nothing in this area.
 - the azure profiles do not generate artifacts but does the same check of the extension (check that it contain necessary files)

What are your thoughts ?

**Comment by danixeee** [comment]
I agree, we should keep only one. I prefer the one which is faster and have better open-source plan.

> appveyor pipeline builds a .vsix of the sample json extension ( https://ci.appveyor.com/project/oll-team/pygls/builds/30402659/artifacts ) on appveyor this is only for windows. The steps to build the extension are written in powershell and it did not seem easy to make this work on linux so I did nothing in this area.

I think we could reuse some parts of code from [here](https://github.com/textX/textX-LS/blob/master/azure-pipelines.yml#L78) to build and upload _vsix_ artifact,  but that's not urgent since I am building it locally during reviews.

**Comment by danixeee** [comment]
@perrinjerome Sorry for the delay. We have created [project](https://dev.azure.com/openlawlibrary/pygls) in Azure devops, but I am not able to load yaml file from forked repository's branch.

If everything is ready, please update your branch and create a PR. I will merge both _azure_ and _appveyor_ scripts to the master branch and make some changes after that.

**Comment by perrinjerome** [comment]
@danixeee I updated this branch ( rebased on master ) and marked this PR "Ready for review".

**Pull request merged**
