### PR TITLE
Only pass the id parameter to types that use it

### PR DESCRIPTION
**Pull request by dcermak**
## Description (e.g. "Related to ...", etc.)

Only pass the `id` parameter to types that use it

## Code review checklist (for code reviewer to complete)

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated, as appropriate
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly
- [ ] [CONTRIBUTORS.md][contributors] was updated, as appropriate
- [ ] Changelog has been updated, as needed (see [CHANGELOG.md][changelog])

[changelog]: https://github.com/openlawlibrary/pygls/blob/master/CHANGELOG.md
[commit messages]: https://chris.beams.io/posts/git-commit/
[contributors]: https://github.com/openlawlibrary/pygls/blob/master/CONTRIBUTORS.md

### CODE REVIEW

**Comment by tombh** [comment]
Right, so the context for this issue is https://github.com/openlawlibrary/pygls/issues/312

This is ready to merge then. Would you like to add yourself to CONTRIBUTORS.md and update CHANGELOG.md?

**Comment by dcermak** [comment]
> This is ready to merge then. Would you like to add yourself to CONTRIBUTORS.md and update CHANGELOG.md?

Should be done. Could you approve the CI please?

**Comment by nodeg** [comment]
@tombh Would you mind enabling the GitHub Actions for this PR, please, so we can proceed with it?

**Comment by tombh** [comment]
I don't have that option in the UI. I assume that's because it's still in Draft status?

**Comment by alcarney** [comment]
Just repeating what I said in #312, I don't think this PR is necessary.

I would argue that the behavior seen in the original issue is expected as `textDocument/didOpen` is a notification, not a request ([see spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didOpen)) and that the [notify](https://github.com/openlawlibrary/pygls/blob/master/pygls/protocol.py#L553) method should be used instead (or even the [text_document_did_save](https://github.com/openlawlibrary/pygls/blob/d5a1212ab85a391e57434eb75f23fc93dfb6f99a/pygls/lsp/client.py#L1964) method on the new Client when that becomes available)

That said, [later on](https://github.com/openlawlibrary/pygls/issues/312#issuecomment-1400630805) in the same thread @dcermak followed up with 

>Ah, thank you! I have switched to using notify, which fixes the runtime error, but sadly it creates a new one: The notify function is synchronous, but the processing of that notification happens asynchronously in the background. So the tests that run immediately after that fail, as the document has not yet been loaded. This worked with send_request, albeit of course only accidentally. Can I somehow wait for the result of that notification to be processed?

But that's probably a separate issue around writing tests involving notifications?

**Pull request closed without merging**
