### PR TITLE
add instructions to README for using text files with vscode-playground

### PR DESCRIPTION
**Pull request by RossBencina**

### CODE REVIEW

**Comment by tombh** [comment]
Thank you. This just needs the commit message to be updated, [see the CI report here](https://github.com/openlawlibrary/pygls/actions/runs/6048498363/job/16420049493?pr=366). Basically something like:
`docs: using text files with vscode-playground `

**Review by alcarney — APPROVED** [review]

**Comment by RossBencina** [comment]
@tombh done.

**Comment by dhruvmanila** [comment]
Not sure if this can be added in this PR itself but for `inlay_hints.py` server, we need the notebook document selector as well:
```json
"pygls.client.documentSelector": [
    {
        "notebook": "*",
        "language": "python"
    }
]
```

**Comment by RossBencina** [comment]
This is just a fix for the README let's leave it at that.

**Comment by alcarney** [comment]
Thanks!

**Pull request merged**
