### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dimbleby**
## Description (e.g. "Related to ...", etc.)

Update dependencies.

I had intended just to pick up the 1.9.0 release of pydantic; but then while I was here, why not also update all the other things too?

I also shuffled mypy configuration so that it all happens in a single file, which seems to me less confusing than spreading it across two (one of them hidden).

And then, because I was double-checking that the sphinx upgrade didn't break anything, I fixed a couple of typos and a missing reference in the docs.

## Code review checklist (for code reviewer to complete)

- [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [x] Title summarizes what is changing
- [x] Commit messages are meaningful (see [this][commit messages] for details)
- [x] Tests have been included and/or updated, as appropriate
- [x] Docstrings have been included and/or updated, as appropriate
- [x] Standalone docs have been updated accordingly
- [x] [CONTRIBUTORS.md][contributors] was updated, as appropriate
- [x] Changelog has been updated, as needed (see [CHANGELOG.md][changelog])

[changelog]: https://github.com/openlawlibrary/pygls/blob/master/CHANGELOG.md
[commit messages]: https://chris.beams.io/posts/git-commit/
[contributors]: https://github.com/openlawlibrary/pygls/blob/master/CONTRIBUTORS.md

### CODE REVIEW

**Comment by dimbleby** [comment]
Looks like python3.6 and ws 10 don't play together, I'll back that upgrade out.

However that python 3.6 is now end of life, you might reasonably consider dropping support for it (and adding 3.10)?

**Comment by perrinjerome** [comment]
This also seems good , it solves the same problem as https://github.com/openlawlibrary/pygls/pull/229 and fix a few other small things at the same time ( but I'm an external contributor and I can not merge )

**Comment by dimbleby** [comment]
Made some more updates, on account of (i) time having passed and (ii) signs of activity in the repository.

- dropped support for python 3.6, added 3.10, specified this in setup.cfg
  - this fixes #234, since it's now explicit that 3.11 is not (yet) supported

- require pydantic 1.9.1.  I'd previously not bumped the minimum version, but now need to do so because https://github.com/samuelcolvin/pydantic/issues/3528
  - arguably we only need recent pydantic in dev, this is specifically a problem with the mypy plugin
  - but I expect that it's not particularly controversial to use a recent pydantic anyway

- bumped other things that have moved on since January

- (minor reformatting in setup.cfg for consistency)

**Comment by tombh** [comment]
This is great, LGTM. It will also fix #229 and #235. Might it even fix #237 (poorly handled `TimeoutError`)? Though I did notice that there was [one CI timeout](https://github.com/openlawlibrary/pygls/runs/6780405031?check_suite_focus=true) with the latest update commit. Curiously it's not mentioned here in the discussion UI, that's confusing. Either way, I'm assured that this PR doesn't trigger any regressions as tracked by the tests.

Would you like to take care of these last small things:
  - [ ] Rebase latest master into the branch
  - [ ] Tidy up the commits, just a squash is fine, or if you feel like it; 1 commit for the Python version support change, 1 commit for the dependency update, and 1 for the typos
  - [ ] Update `python-version: ["3.6", "3.7", "3.8", "3.9"]` stanza in `.github/workflows/ci.yml`
  - [ ] Commit message bodies briefly explaining the changes. Also a `Fixes #229 #235` should auto close those issues

**Comment by dimbleby** [comment]
python-version is already updated in ci.yml isn't it?  what change are you asking for?

you should be able to squash this yourself if you want with the "merge and squash" button, and write whatever summary comment you want

I'm not at the right computer at the moment to do a rebase.  Looks like the merge should be clean though, is a linear history particularly important to you?  (It looks as though that hasn't historically been the case in this repository).

**Review by tombh — APPROVED** [review]

**Comment by tombh** [comment]
> python-version is already updated in ci.yml isn't it? what change are you asking for?

Oh yes! Sorry, I just saw the still "Expected" test runs for Python 3.6 and assumed `ci.yml` wasn't updated, but I expect that's just Github offering some security by not using CI config updates from external PRs.

I've rebased master, squashed the commits and forced-pushed (I still have a backup copy of the original branch).

Personally I prefer linear history, so will try to encourage it, but understand it's not everybody's preference.

Just waiting for the nod from the rest of the team, then I'll manually merge this to override the unrun 3.6 tests...

**Comment by dimbleby** [comment]
per earlier comment: I think that saying which checks are "required" is a setting on the repository, someone with power to do so would need to update the configuration

**Comment by renatav** [comment]
See https://github.com/openlawlibrary/pygls/actions/runs/2461835346

Only running 3.7-3.10 and the builds are passing. So looks like a reporting issue. I don't think that there is a specific setting. Let's merge

**Pull request merged**
