### PR TITLE
Remove dependency on `typeguard`

### PR DESCRIPTION
**Pull request by karthiknadig**
## Description (e.g. "Related to ...", etc.)

Remove dependency on `typeguard`.
fixes https://github.com/openlawlibrary/pygls/issues/409

## Code review checklist (for code reviewer to complete)

- [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [x] Title summarizes what is changing
- [x] Commit messages are meaningful (see [this][commit messages] for details)
- [x] Tests have been included and/or updated, as appropriate
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly

[commit messages]: https://conventionalcommits.org/

### CODE REVIEW

**Comment by tombh** [comment]
Great, thanks. Just request a review from me or Alex when this is ready.

**Comment by karthiknadig** [comment]
@tombh I don't have permissions to add reviewers. This is ready now for review.

**Review by tombh — APPROVED** [review]

**Comment by tombh** [comment]
Oh, sorry, I didn't realise. It looks good, I've approved it. I'll just wait a bit in case Alex gets a chance to look too.

**Review by alcarney — APPROVED** [review]

**Comment by tombh** [comment]
Would you like a Pygls release? Or wait a bit for some bleeding edge testers?

**Comment by karthiknadig** [comment]
I will do more tests with a few servers and let you know.

**Comment by karthiknadig** [comment]
I tested this on a few different servers. It seems to be working as expected.

**Comment by tombh** [comment]
Great, thank you. Here's the PR for the release https://github.com/openlawlibrary/pygls/pull/412

**Pull request merged**
