### PR TITLE
ci: Test against Python 3.12

### PR DESCRIPTION
**Pull request by alcarney**
## Description (e.g. "Related to ...", etc.)

It won't be long now before Python 3.12 becomes available (see [schedule](https://peps.python.org/pep-0693/#schedule))

By making use of the [`allow-prereleases`](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases) flag to `actions/setup-python`, we should be able to start testing on the pre-release version of Python now and have the pipeline automatically upgrade to the real thing when it becomes available

## Code review checklist (for code reviewer to complete)

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated, as appropriate
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly

[commit messages]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by alcarney** [comment]
@tombh any ideas why all the CI pipelines would be running against Python 3.9.17? 
e.g here is the Python 3.8 pipline https://github.com/openlawlibrary/pygls/actions/runs/5813873464/job/15762361442?pr=358#step:7:16

**Comment by tombh** [comment]
Oh 😲 Literally the entire matrix is running against `3.9.17`, wow.

My hunch is that this is a cache key not capturing the Python version from the matrix. There's [a line above in the CI logs](https://github.com/openlawlibrary/pygls/actions/runs/5813873464/job/15762361442?pr=358#step:5:21), that says the cache key is this: `venv-Linux--24170221692f39b8a4570480d97e20d9bf32d65427c4446b210f7445a31547b3`. That double hyphen betrays the missing token value from [our workflow yaml](https://github.com/openlawlibrary/pygls/blob/main/.github/workflows/ci.yml#L47) that defines the key: `key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}`.

I wonder if `steps.setup-python.outputs.python-version` could just be replaced with `matrix.python-version`?

**Comment by alcarney** [comment]
> I wonder if steps.setup-python.outputs.python-version could just be replaced with matrix.python-version?

Good spot! That looks like it did the trick! :smile:

**Review by tombh — APPROVED** [review]

**Comment by tombh** [comment]
Nice spot from you to see it in the first place! 🤓

**Pull request merged**
