### PR TITLE
chore(ci): bust cache

### PR DESCRIPTION
**Pull request by tombh**
Having problems in CI, looks like a bug got cached, hopefully just busting the cache fixes it.

### CODE REVIEW

**Comment by tombh** [comment]
Actually, wait, I have another idea. Why not make `-bustme` be a Actions ENV var, so we can bust the cache just by changing the var in settings! I'll push that when I get a moment soon...

**Comment by alcarney** [comment]
Also, if you know which cache is bad you should be able to delete it from here - https://github.com/openlawlibrary/pygls/actions/caches

**Comment by alcarney** [comment]
I think the cache must be capturing the exact version of Python - (the [Windows error message](https://github.com/openlawlibrary/pygls/actions/runs/6122748751/job/16619306003#step:7:13) seems more useful)

>  No Python at '"C:\hostedtoolcache\windows\Python\3.11.4\x64\python.exe'

Which makes sense when you see that [earlier](https://github.com/openlawlibrary/pygls/actions/runs/6122748751/job/16619306003#step:3:10) in the run Python 3.11.5 was installed

> Successfully set up CPython (3.11.5)

Is there a way for us to get the minor Python version number into the cache key? I wonder if `actions/setup-python` exports that as a step output :thinking:

**Comment by tombh** [comment]
I didn't know about that cache page! That's really good to know.

And fantastic you found the underlying cause, I added the minor version to the cache key like you suggested.

**Review by alcarney — APPROVED** [review]

**Pull request merged**
