### PR TITLE
feat: add workspace symbol resolve

### PR DESCRIPTION
**Pull request by karthiknadig**
## Description (e.g. "Related to ...", etc.)

Add support for workspace symbol resolve request.

## Code review checklist (for code reviewer to complete)

- [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [x] Title summarizes what is changing
- [x] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated, as appropriate
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly

[commit messages]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by karthiknadig** [comment]
@alcarney @tombh I did not see a test for workspace symbol, this change updates existing support for workspace symbol to enable resolve if "workspaceSymbol/resolve" is implemented.

**Comment by tombh** [comment]
Great, thank you. It looks like a pretty straightforward change. Just needs a rebase of main and we can get this merged?

**Comment by karthiknadig** [comment]
@tombh re-based to main.

**Comment by tombh** [comment]
Damn, needs rebasing again! Busy day for that `pygls/capabilities.py` file, which is great 💪

Also, does this contribute to the LSP 3.17 support as well? Outlined in https://github.com/openlawlibrary/pygls/issues/346

**Comment by karthiknadig** [comment]
@tombh The diagnostics has two parts document diagnostics (covered in PR https://github.com/openlawlibrary/pygls/pull/360) and workspace diagnostics (covered by this one).

**Review by tombh — APPROVED** [review]

**Comment by tombh** [comment]
Great 🎉 Thank you.

**Pull request merged**
