### PR TITLE
Initial draft of a migration guide

### PR DESCRIPTION
**Pull request by alcarney**
## Description (e.g. "Related to ...", etc.)

Here's an initial attempt at a migration guide for the 1.0 branch.

- The table of renamed types and constants was manually generated so I may have missed some and there could be errors.
  There's a also a few types I couldn't find obvious replacements for (I probably didn't look hard enough) so some help reviewing this table in particular would be appreciated :slightly_smiling_face: 
- Have I missed anything obvious?

## Code review checklist (for code reviewer to complete)

- [ ] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [ ] Title summarizes what is changing
- [ ] Commit messages are meaningful (see [this][commit messages] for details)
- [ ] Tests have been included and/or updated, as appropriate
- [ ] Docstrings have been included and/or updated, as appropriate
- [ ] Standalone docs have been updated accordingly
- [ ] [CONTRIBUTORS.md][contributors] was updated, as appropriate
- [ ] Changelog has been updated, as needed (see [CHANGELOG.md][changelog])

[changelog]: https://github.com/openlawlibrary/pygls/blob/master/CHANGELOG.md
[commit messages]: https://chris.beams.io/posts/git-commit/
[contributors]: https://github.com/openlawlibrary/pygls/blob/master/CONTRIBUTORS.md

### CODE REVIEW

**Comment by tombh** [comment]
This is excellent. It communicates the main points clearly and succinctly. It looks so approachable written out like this.

* I had a look into those missing types, do any of these look right?
```rst
.. https://github.com/microsoft/lsprotocol/blob/main/lsprotocol/types.py#L7647
``InsertTextModeSupportClientCapabilities``                         ``CompletionClientCapabilitiesCompletionItemTypeInsertTextModeSupportType``
.. https://github.com/microsoft/lsprotocol/blob/main/lsprotocol/types.py#L8077
``ResolveSupportClientCapabilities``                                ``CodeActionClientCapabilitiesResolveSupportType``
.. https://github.com/microsoft/lsprotocol/blob/main/lsprotocol/types.py#L5744
``WorkspaceServerCapabilities``                                     ``ServerCapabilitiesWorkspaceType``
.. I think this is `ServerCapabilitiesWorkspaceType.file_operations`? https://github.com/microsoft/lsprotocol/blob/main/lsprotocol/types.py#L5753
``WorkspaceFileOperationsServerCapabilities``                       ``FileOperationOptions``
```

* How about replacing occurrences of `Sphinx` with `Example`?

**Comment by alcarney** [comment]
> do any of these look right?

Brilliant thanks! Told you I didn't look hard enough :wink: 

> How about replacing occurrences of Sphinx with Example?

Done

**Review by tombh — APPROVED** [review]

**Comment by tombh** [comment]
That's great, glad I managed to find the right types! So merge this into the v1 branch then? Still can add updates to this on that branch, so it's an easy decision to merge I think?

**Comment by alcarney** [comment]
Yes I think so, are we able to publish the 1.0 branch to readthedocs? So that people have the option to use the guide before the release?

**Comment by tombh** [comment]
Excellent idea, it should be possible, I'll look into it.

**Comment by tombh** [comment]
@dgreisen I think the Pygls docs are automagically published by readthedocs.io by a webhook?

So one way to get the migration guide live would be to just cherry-pick that commit into master.

**Comment by dgreisen** [comment]
@tombh - It looks like all you need to do is rename the branch. See https://docs.readthedocs.io/en/stable/versions.html?highlight=alpha#how-we-envision-versions-working

**Comment by tombh** [comment]
Oh right, that's a better idea. Would you like to give me access? My readthedocs.org username is @tombh

**Pull request merged**
