### PR TITLE
some type-checking fixes

### PR DESCRIPTION
**Pull request by dimbleby**
A handful of type-checking fixes.

There's lots more that could be done - try `mypy --strict pygls` if you want to see.  But this covers enough of the public API that typechecking from jedi-language-server is happy.

### CODE REVIEW

**Review by tombh — DISMISSED** [review]

**Comment by tombh** [comment]
Thank you. Do you need these in a release? Would you like to add the conventional commit tag, bump the patch version and add a quick note to the CHANGELOG? I can get it released straight away then.

And yes, `mypy --strict` support is definitely something I'd like to see at some point.

**Comment by dimbleby** [comment]
No hurry at all, I'm just passing the time and making myself useful

**Comment by tombh** [comment]
Could you rebase latest master? Then I'll get this merged. I know we don't yet require commit message syntax. But could you add a `chore:` please. [I'd like for us to start requiring Conventional Commit syntax](https://github.com/openlawlibrary/pygls/issues/300#issuecomment-1338172108) in order to auto generate the CHANGELOG file.

**Review by tombh — APPROVED** [review]

**Comment by tombh** [comment]
Great, thank you ✨

**Pull request merged**
