### PR TITLE
Added the build deps to setup.cfg to make setuptools to update themselves if needed and install other build dependencies.

### PR DESCRIPTION
**Pull request by KOLANICH**
## Description (e.g. "Related to ...", etc.)

Related to: #189

## Code review checklist (for code reviewer to complete)

- [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR)
- [x] Title summarizes what is changing
- [x] Commit messages are meaningful (see [this][commit messages] for details)
- [x] Tests have been included and/or updated, as appropriate
- [x] Docstrings have been included and/or updated, as appropriate
- [x] Standalone docs have been updated accordingly
- [ ] [CONTRIBUTORS.md][contributors] was updated, as appropriate
- [ ] Changelog has been updated, as needed (see [CHANGELOG.md][changelog])

[changelog]: https://github.com/openlawlibrary/pygls/blob/master/CHANGELOG.md
[commit messages]: https://chris.beams.io/posts/git-commit/
[contributors]: https://github.com/openlawlibrary/pygls/blob/master/CONTRIBUTORS.md

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Commit message is incorrect -- no (currently existing) version of setuptools supports pyproject.toml, though there is an open ticket to consider doing so.

The issue is:
- pyproject.toml build-system.requires specifies what you need in order to run the build backend
- build-system.requires is installed, build-system.build-backend is run to query additional `get_requires_for_build_sdist()` / `get_requires_for_build_wheel()`, which means setup.cfg "setup_requires"
- these additional requires are then installed, and the `build_sdist()` / `build_wheel()` hooks are run

If people use the setup.py directly, then
- setuptools tries to require/install/fail if unavailable, the setup_requires directly rather than sending them to the pep517 build frontend
- these additional requires are then installed
- sdist / bdist_wheel methods are run

**Comment by danixeee** [comment]
@KOLANICH @eli-schwartz When I install `pygls` with `pip install .` command I get the correct version

```bash
(TEST) Daniels-MacBook-Pro:pygls daniel$ pip list
Package           Version
----------------- --------------------
pip               21.1.1
pydantic          1.8.2
pygls             0.10.4.dev3+g2a525bf
setuptools        41.2.0
typeguard         2.12.0
typing-extensions 3.10.0.0
```

but when I run `python setup.py sdist bdist_wheel clean` I get the following wheel name `pygls-0.0.0-py3-none-any.whl`.

 After I ran `pip install setuptools_scm[toml]` and built wheel again I got `pygls-0.10.4.dev3+g2a525bf-py3-none-any.whl`.

1. How to produce `pygls-0.10.4-py3-none-any.whl`?
2. Why we don't fail the build command if requirements are not satisfied by importing needed dependencies in `setup.py`?

**Comment by danixeee** [comment]
@eli-schwartz Thanks for the explanation.

> Of course if you git checkout <tagged_version> and do the same experiment again, it will not be a development version and thus you'll get the pygls-0.10.4-py3-none-any.whl you were curious to create...

Makes sense.

> The point of this PR is so that running python setup.py bdist_wheel will either install setuptools_scm[toml] or fail the build command, and never just say "0.0.0".

I am still not able to build a dist with the correct version. Here's the output:

```bash
Daniels-MacBook-Pro:pygls daniel$ git branch
pr/KOLANICH/191

Daniels-MacBook-Pro:pygls daniel$ pip list
Package            Version
------------------ -------
astroid            2.1.0
atomicwrites       1.3.0
attrs              19.1.0
autopep8           1.4.4
importlib-metadata 0.18
isort              4.3.4
lazy-object-proxy  1.3.1
more-itertools     7.0.0
packaging          19.0
pep8               1.7.1
pip                21.1.1
pluggy             0.12.0
py                 1.8.0
pycodestyle        2.5.0
pylint             2.2.2
pyparsing          2.4.0
setuptools         40.6.3
six                1.12.0
typed-ast          1.1.0
wcwidth            0.1.7
wrapt              1.11.1
zipp               0.5.1

Daniels-MacBook-Pro:pygls daniel$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/pygls
copying pygls/feature_manager.py -> build/lib/pygls
copying pygls/server.py -> build/lib/pygls
copying pygls/protocol.py -> build/lib/pygls
copying pygls/constants.py -> build/lib/pygls
copying pygls/__init__.py -> build/lib/pygls
copying pygls/capabilities.py -> build/lib/pygls
copying pygls/exceptions.py -> build/lib/pygls
copying pygls/workspace.py -> build/lib/pygls
copying pygls/uris.py -> build/lib/pygls
creating build/lib/pygls/lsp
copying pygls/lsp/methods.py -> build/lib/pygls/lsp
copying pygls/lsp/__init__.py -> build/lib/pygls/lsp
creating build/lib/pygls/lsp/types
copying pygls/lsp/types/general_messages.py -> build/lib/pygls/lsp/types
copying pygls/lsp/types/window.py -> build/lib/pygls/lsp/types
copying pygls/lsp/types/diagnostics.py -> build/lib/pygls/lsp/types
copying pygls/lsp/types/client.py -> build/lib/pygls/lsp/types
copying pygls/lsp/types/__init__.py -> build/lib/pygls/lsp/types
copying pygls/lsp/types/basic_structures.py -> build/lib/pygls/lsp/types
copying pygls/lsp/types/text_synchronization.py -> build/lib/pygls/lsp/types
copying pygls/lsp/types/workspace.py -> build/lib/pygls/lsp/types
creating build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/signature_help.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/document_symbol.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/color_presentation.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/completion.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/code_action.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/rename.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/references.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/document_link.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/type_definition.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/__init__.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/folding_range.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/formatting.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/declaration.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/prepare_rename.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/code_lens.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/on_type_formatting.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/document_color.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/implementation.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/definition.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/range_formatting.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/selection_range.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/hover.py -> build/lib/pygls/lsp/types/language_features
copying pygls/lsp/types/language_features/document_highlight.py -> build/lib/pygls/lsp/types/language_features
running egg_info
writing pygls.egg-info/PKG-INFO
writing dependency_links to pygls.egg-info/dependency_links.txt
writing requirements to pygls.egg-info/requires.txt
writing top-level names to pygls.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'pygls.egg-info/SOURCES.txt'
copying pygls/py.typed -> build/lib/pygls
installing to build/bdist.macosx-10.15-x86_64/wheel
running install
running install_lib
creating build/bdist.macosx-10.15-x86_64
creating build/bdist.macosx-10.15-x86_64/wheel
creating build/bdist.macosx-10.15-x86_64/wheel/pygls
copying build/lib/pygls/feature_manager.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls
copying build/lib/pygls/server.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls
copying build/lib/pygls/protocol.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls
copying build/lib/pygls/constants.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls
copying build/lib/pygls/__init__.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls
creating build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp
creating build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types
copying build/lib/pygls/lsp/types/general_messages.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types
copying build/lib/pygls/lsp/types/window.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types
copying build/lib/pygls/lsp/types/diagnostics.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types
copying build/lib/pygls/lsp/types/client.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types
copying build/lib/pygls/lsp/types/__init__.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types
copying build/lib/pygls/lsp/types/basic_structures.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types
copying build/lib/pygls/lsp/types/text_synchronization.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types
copying build/lib/pygls/lsp/types/workspace.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types
creating build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/signature_help.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/document_symbol.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/color_presentation.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/completion.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/code_action.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/rename.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/references.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/document_link.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/type_definition.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/__init__.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/folding_range.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/formatting.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/declaration.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/prepare_rename.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/code_lens.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/on_type_formatting.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/document_color.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/implementation.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/definition.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/range_formatting.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/selection_range.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/hover.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/types/language_features/document_highlight.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp/types/language_features
copying build/lib/pygls/lsp/methods.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp
copying build/lib/pygls/lsp/__init__.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls/lsp
copying build/lib/pygls/capabilities.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls
copying build/lib/pygls/py.typed -> build/bdist.macosx-10.15-x86_64/wheel/pygls
copying build/lib/pygls/exceptions.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls
copying build/lib/pygls/workspace.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls
copying build/lib/pygls/uris.py -> build/bdist.macosx-10.15-x86_64/wheel/pygls
running install_data
creating build/bdist.macosx-10.15-x86_64/wheel/pygls-0.0.0.data
creating build/bdist.macosx-10.15-x86_64/wheel/pygls-0.0.0.data/data
creating build/bdist.macosx-10.15-x86_64/wheel/pygls-0.0.0.data/data/lib
creating build/bdist.macosx-10.15-x86_64/wheel/pygls-0.0.0.data/data/lib/site_packages
creating build/bdist.macosx-10.15-x86_64/wheel/pygls-0.0.0.data/data/lib/site_packages/pygls
copying ThirdPartyNotices.txt -> build/bdist.macosx-10.15-x86_64/wheel/pygls-0.0.0.data/data/lib/site_packages/pygls
copying ./pygls/py.typed -> build/bdist.macosx-10.15-x86_64/wheel/pygls-0.0.0.data/data/lib/site_packages/pygls
running install_egg_info
Copying pygls.egg-info to build/bdist.macosx-10.15-x86_64/wheel/pygls-0.0.0-py3.6.egg-info
running install_scripts
adding license file "LICENSE.txt" (matched pattern "LICEN[CS]E*")
creating build/bdist.macosx-10.15-x86_64/wheel/pygls-0.0.0.dist-info/WHEEL
creating 'dist/pygls-0.0.0-py3-none-any.whl' and adding 'build/bdist.macosx-10.15-x86_64/wheel' to it
adding 'pygls/__init__.py'
adding 'pygls/capabilities.py'
adding 'pygls/constants.py'
adding 'pygls/exceptions.py'
adding 'pygls/feature_manager.py'
adding 'pygls/protocol.py'
adding 'pygls/py.typed'
adding 'pygls/server.py'
adding 'pygls/uris.py'
adding 'pygls/workspace.py'
adding 'pygls/lsp/__init__.py'
adding 'pygls/lsp/methods.py'
adding 'pygls/lsp/types/__init__.py'
adding 'pygls/lsp/types/basic_structures.py'
adding 'pygls/lsp/types/client.py'
adding 'pygls/lsp/types/diagnostics.py'
adding 'pygls/lsp/types/general_messages.py'
adding 'pygls/lsp/types/text_synchronization.py'
adding 'pygls/lsp/types/window.py'
adding 'pygls/lsp/types/workspace.py'
adding 'pygls/lsp/types/language_features/__init__.py'
adding 'pygls/lsp/types/language_features/code_action.py'
adding 'pygls/lsp/types/language_features/code_lens.py'
adding 'pygls/lsp/types/language_features/color_presentation.py'
adding 'pygls/lsp/types/language_features/completion.py'
adding 'pygls/lsp/types/language_features/declaration.py'
adding 'pygls/lsp/types/language_features/definition.py'
adding 'pygls/lsp/types/language_features/document_color.py'
adding 'pygls/lsp/types/language_features/document_highlight.py'
adding 'pygls/lsp/types/language_features/document_link.py'
adding 'pygls/lsp/types/language_features/document_symbol.py'
adding 'pygls/lsp/types/language_features/folding_range.py'
adding 'pygls/lsp/types/language_features/formatting.py'
adding 'pygls/lsp/types/language_features/hover.py'
adding 'pygls/lsp/types/language_features/implementation.py'
adding 'pygls/lsp/types/language_features/on_type_formatting.py'
adding 'pygls/lsp/types/language_features/prepare_rename.py'
adding 'pygls/lsp/types/language_features/range_formatting.py'
adding 'pygls/lsp/types/language_features/references.py'
adding 'pygls/lsp/types/language_features/rename.py'
adding 'pygls/lsp/types/language_features/selection_range.py'
adding 'pygls/lsp/types/language_features/signature_help.py'
adding 'pygls/lsp/types/language_features/type_definition.py'
adding 'pygls-0.0.0.data/data/lib/site_packages/pygls/ThirdPartyNotices.txt'
adding 'pygls-0.0.0.data/data/lib/site_packages/pygls/py.typed'
adding 'pygls-0.0.0.dist-info/LICENSE.txt'
adding 'pygls-0.0.0.dist-info/METADATA'
adding 'pygls-0.0.0.dist-info/WHEEL'
adding 'pygls-0.0.0.dist-info/top_level.txt'
adding 'pygls-0.0.0.dist-info/RECORD'
removing build/bdist.macosx-10.15-x86_64/wheel

Daniels-MacBook-Pro:pygls daniel$ pip list
Package            Version
------------------ -------
astroid            2.1.0
atomicwrites       1.3.0
attrs              19.1.0
autopep8           1.4.4
importlib-metadata 0.18
isort              4.3.4
lazy-object-proxy  1.3.1
more-itertools     7.0.0
packaging          19.0
pep8               1.7.1
pip                21.1.1
pluggy             0.12.0
py                 1.8.0
pycodestyle        2.5.0
pylint             2.2.2
pyparsing          2.4.0
setuptools         40.6.3
six                1.12.0
typed-ast          1.1.0
wcwidth            0.1.7
wrapt              1.11.1
zipp               0.5.1
```

**Comment by eli-schwartz** [comment]
I don't know what to say to you, it works flawlessly for me on python 3.9:

```
$ ./venv/bin/python -m pip list
Package    Version
---------- -------
pip        20.2.3
setuptools 49.2.1
wheel      0.36.2
```

The needed build dependencies end up in the .eggs/ directory, BTW. No need to run pip install anything.

Maybe your extremely old setuptools is the problem? https://setuptools.readthedocs.io/en/latest/history.html#v42-0-2
> #1922: Build dependencies (setup_requires and tests_require) now install transitive dependencies indicated by extras.

I can't test such ancient versions since they fatally error out on modern python, and this project needs >=44 anyway.

**Comment by KOLANICH** [comment]
@eli-schwartz, does it work for you after the latest change? Because when I have uninstalled `setuptools_scm` I started getting errors that `setuptools_scm` has no extra `toml`, so contrary to that is recommended on https://github.com/pypa/setuptools_scm/ instead of `"setuptools_scm[toml]>=6.0"` I have specified `"setuptools_scm", "toml"` in `pyproject.toml` and the analogue in `setup.cfg` and only after that it started building right when `setuptools_scm` is not installed in the system (surprisingly, when `toml` is not installed (for testing purposes I have manually removed even the one installed by `apt`), even `setuptools` doesn't work for any project (including `toml` and `setuptools` themselves) and fail, and setting `PYTHONPATH` doesn't help, it may be a bug in some package, the most likely `pkg_resources` (a part of `setuptools`), from which it was raised ).

@danixeee, could you, please, test it again?

**Comment by eli-schwartz** [comment]
It worked with both versions of the PR. I tested in a virtualenv containing no packages other than the wheels for pip and setuptools bundled by ensurepip, and 'pip install wheel' so that bdist_wheel exists.

**Comment by danixeee** [comment]
> Maybe your extremely old setuptools is the problem? https://setuptools.readthedocs.io/en/latest/history.html#v42-0-2

@eli-schwartz That seems to cause the problem. I updated `setuptools` to `v42.0.2` and it works fine now. Also, I don't need to install `setuptools_scm[toml]` manually.

I am not sure why the build command does not fail if the version of setuptools is not satisfied.

@KOLANICH Could we manually check the dependency on the build command?

```python
#!/usr/bin/env python3

from sys import exit

import setuptools.command.build_py
from setuptools import __version__, setup


class BuildPyCommand(setuptools.command.build_py.build_py):

    def run(self):
        # Check setuptools version (>=42.0.2)
        major, _, patch = map(lambda x: int(x), __version__.split('.'))
        if major < 42 or (major == 42 and patch < 2):
            print('\nError: setuptools>=42.0.2 is required to properly build wheels!\n')
            exit(1)

        setuptools.command.build_py.build_py.run(self)

if __name__ == "__main__":
    setup(
        cmdclass={
            'build_py': BuildPyCommand,
        },
    )
```

**Comment by KOLANICH** [comment]
>@KOLANICH Could we manually check the dependency on the build command?

We can, but IMHO we shouldn't. The ultimate purpose of moving the data into `setup.cfg` was to get rid of `setup.py` entirely.

**Review by danixeee — APPROVED** [review]

**Pull request merged**
